spring:
  application:
    name: ms-reto-aws
  lifecycle:
    timeout-per-shutdown-phase: 20s
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/retoaws}
    username: ${DB_USERNAME:retoaws_app}
    password: ${DB_PASSWORD:retoaws_local}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: retoaws
  flyway:
    enabled: true
    default-schema: retoaws
    schemas: retoaws
    create-schemas: false
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  servlet:
    context-path: ${API_CONTEXT_PATH:/api/v1}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
